#
# Makefile for the BROANDCOM BCM4329 device drivers.
#

obj-$(CONFIG_BROADCOM_BCM4329)				+= bcm4329_bt_power.o
obj-$(CONFIG_BROADCOM_BCM4329_BLUETOOTH_POWER)		+= bcm4329_fm_power.o
obj-$(CONFIG_BROADCOM_BCM4329_WLAN_POWER)		+= bcm4329_wlan_power.o
