#This is new yamaha sensors architecuture
obj-$(CONFIG_INPUT_YAS529) += yas529.o
obj-$(CONFIG_INPUT_BMA150) += bma150.o
obj-$(CONFIG_INPUT_ORIENTATION) += orientation.o
obj-$(CONFIG_INPUT_LIGHT)  += light.o
obj-$(CONFIG_INPUT_PROXIMITY) += proximity.o

#Div2D5-OwenHuang-SF8_Sensor_Porting-00+{
obj-$(CONFIG_SENSORS_CM3623) += cm3623.o
#Div2D5-OwenHuang-SF8_Sensor_Porting-00+}