obj-$(CONFIG_DIAG_CHAR) := diagchar.o
#+{PS3-RR-ON_DEVICE_QXDM-01
#diagchar-objs := diagchar_core.o diagchar_hdlc.o diagfwd.o diagmem.o
diagchar-objs := diagchar_core.o diagchar_hdlc.o diagfwd.o diagmem.o wpdiag.o
#PS3-RR-ON_DEVICE_QXDM-01}+
